export const pokemonTypeIcons: Record<string, any> = {
  fire: require("@/assets/types/fire.svg"),
  water: require("@/assets/types/water.svg"),
  grass: require("@/assets/types/grass.svg"),
  electric: require("@/assets/types/electric.svg"),
  bug: require("@/assets/types/bug.svg"),
  normal: require("@/assets/types/normal.svg"),
  poison: require("@/assets/types/poison.svg"),
  ground: require("@/assets/types/ground.svg"),
  fairy: require("@/assets/types/fairy.svg"),
  fighting: require("@/assets/types/fighting.svg"),
  psychic: require("@/assets/types/psychic.svg"),
  rock: require("@/assets/types/rock.svg"),
  ghost: require("@/assets/types/ghost.svg"),
  ice: require("@/assets/types/ice.svg"),
  dragon: require("@/assets/types/dragon.svg"),
  dark: require("@/assets/types/dark.svg"),
  steel: require("@/assets/types/steel.svg"),
  flying: require("@/assets/types/flying.svg"),
};
